---
title: "Bee swarm"
output: html_notebook
---
```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# The "pacman" package automatically install missing packages and load them
if (!require("pacman")) install.packages("pacman", repos='https://stat.ethz.ch/CRAN/'); library(pacman)
p_load(
       DT,         # for showing data table with navigation/search controls
       tidyr,      # collection of the tidyverse packages:
       dplyr,      #   - for data wrangling
       tibble,     #   - a stricter alternative to data.frame
       readr,      #   - a stricter alternative to read.csv
       broom,      #   - for cleaing output from models, e.g., lm()
       ggplot2,    #   - for plotting
       cowplot,    # adds plot_grid() to put multiple ggplot()'s togeter
       GGally,     # adds ggpairs() which is a smarter scatterplot matrix
       assertthat, # for unit-testing your functions
       car,        # grab bag of useful functions for NHST
       GetoptLong,  # string interpolation. See qq() explanation below
       lubridate   # utility for parsing and performing arithematic on dates 
       )

# string interpolation
qq.options("code.pattern" = "#\\{CODE\\}") 

# plot theme
myTheme <- theme(panel.background = element_blank(), panel.grid.major = element_line(color="lightgrey", size = 0.2))

# decimal output
options(scipen=1, digits=2)

# datatable
options(DT.options = list(pageLength = 10))
options(DT.autoHideNavigation = TRUE)
```

Load beeswarm package
```{r, echo=TRUE}
p_load("beeswarm")  # for "breast" dataset
p_load_gh("eclarke/ggbeeswarm")
```

Show different types of plot
```{r}
# load breast cancer data
data(breast)
breastCancer <- as_tibble(breast)
rm(breast)

pPoint <- breastCancer %>%   
  ggplot(aes(x = ER, y = time_survival)) + 
  geom_point() +
  labs(title = "Point")

pJitter <- breastCancer %>%   
  ggplot(aes(x = ER, y = time_survival)) + 
  geom_jitter(width = 0.2) +
  labs(title = "Jitter")

pBee <- breastCancer %>%   
  ggplot(aes(x = ER, y = time_survival)) + 
  geom_beeswarm() +
  labs(title = "Beeswarm")

pBox <- breastCancer %>%   
  ggplot(aes(x = ER, y = time_survival)) + 
  geom_boxplot() +
  labs(title = "Boxplot")

pHist <- breastCancer %>%   
  ggplot(aes(x = time_survival, fill = ER)) + 
  geom_histogram(binwidth = 10) +
  facet_grid(. ~ ER) +
  coord_flip() +
  labs(title = "Histogram") +
  guides(fill=FALSE)


plot_grid(pPoint, pJitter, pBee, nrow = 1)
plot_grid(pBee, pHist, nrow = 1)
plot_grid(pBee, pBox,nrow = 1)
```

```{r}
set.seed(15)
df <- tibble(
  x = rep(c("A", "B"), each = 50),
  y = c(
    rnorm(25, mean = 10, sd = 1),
    rnorm(25, mean = 20, sd = 1),
    runif(50, min = 5, max = 25)
  )
)


pPoint <- df %>%   
  ggplot(aes(x = x, y = y)) + 
  geom_point() +
  labs(title = "Point")

pJitter <- df %>%   
  ggplot(aes(x = x, y = y)) + 
  geom_jitter(width = 0.2) +
  labs(title = "Jitter")

pBee <- df %>%   
  ggplot(aes(x = x, y = y)) + 
  geom_beeswarm() +
  labs(title = "Beeswarm")

pBox <- df %>%   
  ggplot(aes(x = x, y = y)) + 
  geom_boxplot() +
  labs(title = "Boxplot")

plot_grid(pPoint, pJitter, pBee, pBox,nrow = 1)
```

